import type { AnalyticsEvent, AuditLog, Lead, Listing, MediaAsset, Workspace } from "@/types/domain";

const now = new Date("2026-06-26T12:00:00.000Z").toISOString();

export const demoWorkspace: Workspace = {
  id: "workspace_rare_address",
  name: "The Rare Address",
  slug: "the-rare-address",
  city: "Pune",
  ownerId: "user_owner_demo",
  logoURL: "",
  contactName: "Deepak S.",
  contactPhone: "9822052388",
  contactEmail: "hello@therealestatelink.local",
  websiteTheme: "premium",
  customDomain: null,
  planId: "pro",
  status: "active",
  createdAt: now,
  updatedAt: now,
};

export const demoMedia: MediaAsset[] = [
  {
    id: "media_garden_flat_hero",
    workspaceId: demoWorkspace.id,
    listingId: "listing_garden_flat",
    intakeSessionId: "intake_demo",
    url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1800&auto=format&fit=crop",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=600&auto=format&fit=crop",
    storagePath: "demo/listings/garden-flat/hero.jpg",
    type: "image",
    order: 0,
    roomType: "garden",
    qualityScore: 92,
    isHero: true,
    caption: "Ground floor home with attached open garden area",
    uploadedBy: "user_owner_demo",
    source: "whatsapp",
    createdAt: now,
  },
  {
    id: "media_garden_flat_living",
    workspaceId: demoWorkspace.id,
    listingId: "listing_garden_flat",
    intakeSessionId: "intake_demo",
    url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=1400&auto=format&fit=crop",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=600&auto=format&fit=crop",
    storagePath: "demo/listings/garden-flat/living.jpg",
    type: "image",
    order: 1,
    roomType: "living room",
    qualityScore: 86,
    isHero: false,
    caption: "Bright interiors with an independent-house feel",
    uploadedBy: "user_owner_demo",
    source: "whatsapp",
    createdAt: now,
  },
  {
    id: "media_garden_flat_kitchen",
    workspaceId: demoWorkspace.id,
    listingId: "listing_garden_flat",
    intakeSessionId: "intake_demo",
    url: "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?q=80&w=1400&auto=format&fit=crop",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?q=80&w=600&auto=format&fit=crop",
    storagePath: "demo/listings/garden-flat/kitchen.jpg",
    type: "image",
    order: 2,
    roomType: "kitchen",
    qualityScore: 82,
    isHero: false,
    caption: "Functional kitchen connected to the main living area",
    uploadedBy: "user_owner_demo",
    source: "whatsapp",
    createdAt: now,
  },
  {
    id: "media_garden_flat_bedroom",
    workspaceId: demoWorkspace.id,
    listingId: "listing_garden_flat",
    intakeSessionId: "intake_demo",
    url: "https://images.unsplash.com/photo-1615873968403-89e068629265?q=80&w=1400&auto=format&fit=crop",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1615873968403-89e068629265?q=80&w=600&auto=format&fit=crop",
    storagePath: "demo/listings/garden-flat/bedroom.jpg",
    type: "image",
    order: 3,
    roomType: "bedroom",
    qualityScore: 84,
    isHero: false,
    caption: "Calm bedroom proportions for family use",
    uploadedBy: "user_owner_demo",
    source: "whatsapp",
    createdAt: now,
  },
  {
    id: "media_garden_flat_exterior",
    workspaceId: demoWorkspace.id,
    listingId: "listing_garden_flat",
    intakeSessionId: "intake_demo",
    url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1400&auto=format&fit=crop",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=600&auto=format&fit=crop",
    storagePath: "demo/listings/garden-flat/exterior.jpg",
    type: "image",
    order: 4,
    roomType: "building exterior",
    qualityScore: 88,
    isHero: false,
    caption: "Low-rise residential setting with independent-home character",
    uploadedBy: "user_owner_demo",
    source: "whatsapp",
    createdAt: now,
  },
];

export const demoListings: Listing[] = [
  {
    id: "listing_garden_flat",
    workspaceId: demoWorkspace.id,
    title: "Rare Corner Ground Floor Flat with 1200 Sqft Attached Garden",
    slug: "rare-corner-ground-floor-flat-parmar-residency",
    status: "published",
    transactionType: "sale",
    propertyType: "apartment",
    location: "Parmar Residency, near Salunke Vihar Road, Pune",
    city: "Pune",
    locality: "Salunke Vihar Road",
    societyName: "Parmar Residency",
    googleMapsUrl: "",
    price: 9000000,
    deposit: null,
    brokerage: "2%",
    taxes: "extra",
    bhk: 3,
    bedrooms: 3,
    bathrooms: 2,
    carpetArea: 515,
    builtUpArea: null,
    plotArea: 1700,
    openArea: 1200,
    furnishedStatus: null,
    parkingCount: 1,
    floor: "ground",
    totalFloors: null,
    availability: "Immediate",
    preferredTenant: null,
    descriptionShort:
      "A rare ground floor corner home with compact built space and a substantial attached garden area.",
    descriptionLong:
      "This ground floor corner flat pairs a 515 sqft constructed home with an approximately 1200 sqft attached open garden area. It is three-side open, naturally bright, and suited to buyers who want an independent-house feeling inside a society setting.",
    highlights: [
      "1200 sqft attached open garden area",
      "Corner flat with three-side openness",
      "Separate entry and exit access",
      "Reserved car parking",
    ],
    amenities: ["Natural light", "Ventilation", "Car parking", "Garden access"],
    missingFields: ["maintenance", "property age", "garden ownership confirmation"],
    riskFlags: ["attached_open_area", "future_expansion", "separate_entry_exit"],
    confirmationQuestions: [
      "Is the 1200 sqft open area legally owned, exclusive-use, or society-allotted?",
      "Is the attached open area mentioned in the sale deed or Index 2?",
      "Is future construction allowed by society and municipal authorities?",
    ],
    qualityScore: 82,
    confidenceScore: 0.88,
    views: 1248,
    leads: 18,
    whatsappClicks: 46,
    callClicks: 22,
    assignedTo: "user_sales_demo",
    createdBy: "user_owner_demo",
    publishedAt: now,
    expiresAt: "2026-07-26T12:00:00.000Z",
    lastConfirmedAt: now,
    freshnessStatus: "Updated today",
    seoTitle: "Rare Ground Floor Garden Flat in Pune | therealestatelink",
    seoDescription:
      "View a rare corner ground floor flat near Salunke Vihar Road with attached garden area.",
    whatsappShareText:
      "Rare corner ground floor flat with 1200 sqft attached garden in Pune.",
    instagramCaption:
      "Rare Pune find: ground floor corner flat with attached garden area.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "listing_baner_rental",
    workspaceId: demoWorkspace.id,
    title: "Furnished 2 BHK Near Baner High Street",
    slug: "furnished-2-bhk-baner-high-street",
    status: "ready_to_publish",
    transactionType: "rent",
    propertyType: "apartment",
    location: "Baner High Street, Pune",
    city: "Pune",
    locality: "Baner",
    societyName: "High Street Residences",
    googleMapsUrl: "",
    price: 52000,
    deposit: 150000,
    brokerage: "1 month",
    taxes: "",
    bhk: 2,
    bedrooms: 2,
    bathrooms: 2,
    carpetArea: 890,
    builtUpArea: null,
    plotArea: null,
    openArea: null,
    furnishedStatus: "furnished",
    parkingCount: 1,
    floor: "7",
    totalFloors: 12,
    availability: "From 1 July 2026",
    preferredTenant: "Family or company lease",
    descriptionShort: "A move-in ready 2 BHK close to Baner offices and cafes.",
    descriptionLong:
      "A furnished apartment with parking, good natural light, and quick access to Baner High Street.",
    highlights: ["Furnished", "Prime Baner location", "Reserved parking"],
    amenities: ["Lift", "Security", "Parking"],
    missingFields: ["maintenance"],
    riskFlags: [],
    confirmationQuestions: [],
    qualityScore: 76,
    confidenceScore: 0.81,
    views: 312,
    leads: 5,
    whatsappClicks: 12,
    callClicks: 6,
    assignedTo: "user_sales_demo",
    createdBy: "user_listing_demo",
    publishedAt: null,
    expiresAt: null,
    lastConfirmedAt: null,
    freshnessStatus: "Draft",
    seoTitle: "Furnished 2 BHK in Baner | therealestatelink",
    seoDescription: "Move-in ready furnished 2 BHK near Baner High Street.",
    whatsappShareText: "Furnished 2 BHK near Baner High Street available for rent.",
    instagramCaption: "Move-in ready 2 BHK in Baner.",
    createdAt: now,
    updatedAt: now,
  },
];

export const demoLeads: Lead[] = [
  {
    id: "lead_aarav",
    name: "Aarav Shah",
    phone: "9876543210",
    email: "aarav@example.com",
    message: "Can we schedule a visit this Sunday?",
    preferredVisitDate: "2026-06-28",
    budget: 9500000,
    contactConsent: true,
    marketingConsent: false,
    consentVersion: "lead-enquiry-v1",
    consentedAt: now,
    source: "public_listing",
    listingId: "listing_garden_flat",
    workspaceId: demoWorkspace.id,
    assignedTo: "user_sales_demo",
    status: "visit_scheduled",
    notes: ["Interested in garden rights confirmation."],
    followUpAt: "2026-06-27T10:00:00.000Z",
    createdAt: now,
    updatedAt: now,
  },
];

export const demoAnalyticsEvents: AnalyticsEvent[] = [
  { id: "event_1", workspaceId: demoWorkspace.id, listingId: "listing_garden_flat", type: "listing_view", createdAt: now },
  { id: "event_2", workspaceId: demoWorkspace.id, listingId: "listing_garden_flat", type: "whatsapp_click", createdAt: now },
  { id: "event_3", workspaceId: demoWorkspace.id, listingId: "listing_garden_flat", type: "enquiry_submit", createdAt: now },
];

export const demoAuditLogs: AuditLog[] = [
  {
    id: "audit_publish",
    workspaceId: demoWorkspace.id,
    actorId: "user_owner_demo",
    action: "listing_published",
    targetId: "listing_garden_flat",
    createdAt: now,
  },
  {
    id: "audit_ai",
    workspaceId: demoWorkspace.id,
    actorId: "system",
    action: "ai_generation_completed",
    targetId: "listing_garden_flat",
    createdAt: now,
  },
];
